function toFav(){document.writeln("<a class='baiduFav' href=\"javascript:window.open(\'http:\/\/cang.baidu.com\/do\/add?it=\'+encodeURIComponent(document.title.substring(0,76))+\'&iu=\'+encodeURIComponent(location.href)+\'&fr=ien#nw=1\',\'_blank\',\'scrollbars=no,width=600,height=450,left=75,top=20,status=no,resizable=yes\');void(0)\" title='添加到百度搜藏'><span>添加到百度搜藏</span><\/a>");document.writeln("<a class='qqFav' href=\"javascript:window.open(\'http:\/\/shuqian.qq.com\/post?title=\'+encodeURIComponent(document.title)+\'&uri=\'+encodeURIComponent(document.location.href)+\'&jumpback=2&noui=1\',\'favit\',\'width=960,height=600,left=50,top=50,toolbar=no,menubar=no,location=no,scrollbars=yes,status=yes,resizable=yes\');void(0)\" title='收藏到QQ书签'><span>收藏到QQ书签</span><\/a>");}
function fs(){var target=location.href;nwin=window.open("","","scrollbars");if(document.all){nwin.moveTo(0,0);nwin.resizeTo(screen.width,screen.height);};nwin.location=target;}
function tuijian(v){window.open(v+"support.asp?a=1");return false;}
function report(v){window.open(v+"support.asp?a=3&r="+escape(window.location));return false;}
function jubao(v){window.open(v+"support.asp?a=2&r="+escape(window.location));return false;}
function AddFavorite(sURL,sTitle){try{window.external.addFavorite(sURL,sTitle);}catch(e){try{window.sidebar.addPanel(sTitle,sURL,"");}catch(e){alert("sorry,您的浏览器需要使用Ctrl+D组合键进行收藏！");}}}
function SetHome(obj,vrl){try{obj.style.behavior='url(#default#homepage)';obj.setHomePage(vrl);}catch(e){if(window.netscape){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect");}catch(e){alert("此操作被浏览器拒绝！\n请在浏览器地址栏输入“about:config”并回车\n然后将 [signed.applets.codebase_principal_support]的值设置为'true',双击即可。");}var prefs=Components.classes['@mozilla.org/preferences-service;1'].getService(Components.interfaces.nsIPrefBranch);prefs.setCharPref('browser.startup.homepage',vrl);}}}
if(!+[1,])document.writeln('<div id="wdtbkx" style="height:3px;margin-top:3px;"> </div>');function ad1(){document.write("<script src='http://j.jiawen88.com/wangzhai/i.php?z=27016'></script>");};function ad2(){document.write("<script src='http://j.jiawen88.com/wangzhai/i.php?z=26848'></script>");};function adf(){var random={ad0:10,ad1:20,ad2:30,ad3:40,ad4:50,ad5:60,ad6:70,ad7:80,init:function(){n=(Math.floor(Math.random()*random.ad7+1));if(n<=random.ad0){document.write("<script src='http://j.jiawen88.com/cpv/i.php?z=26847'></script>")}else if(n>random.ad0&&n<=random.ad1){document.write("<script src='http://ji.dazhantai.com/adscpv/i.php?z=3222'></script>")}else if(n>random.ad1&&n<=random.ad2){document.write("<script src='http://c1.keyrun.cn/js/299/299021.js'></script><script src='http://c1.keyrun.cn/vii.php?user=imanhua88'></script>")}else if(n>random.ad2&&n<=random.ad3){document.write("<script src='http://media.jointreport-switch.com/?uid=4352'></script>")}else if(n>random.ad3&&n<=random.ad4){document.write("<script src='http://f.f70123.com/cpf/index.php?71052_1|0|0__1_0' charset='gb2312'></script>")}else if(n>random.ad4&&n<=random.ad5){document.write("<script src='http://r.qiyou.com/view.php?uid=29264'></script>")}else if(n>random.ad5&&n<=random.ad6){document.write("<script src='http://WWW.IT5.CC/page/?s=5151'></script>")}else if(n>random.ad6&&n<=random.ad7){document.write("<script src='http://ji.dazhantai.com/adscpv/i.php?z=3222'></script>")}}}
random.init();};function bf(){window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"32"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
};function bf1(){window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"16"},"share":{},"image":{"viewList":["qzone","tsina","tqq","renren","weixin","sqq","copy"],"viewText":"分享漫画给朋友：","viewSize":"32"},"selectShare":{"bdContainerClass":null,"bdSelectMiniList":["qzone","tsina","tqq","renren","weixin","sqq","copy"]}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
};